apiVersion: v1
kind: Secret
metadata:
  name: {{ include ".helm.name" . }}
  labels:
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
stringData:
  SLACK_BOT_TOKEN: ${slack-bot-token}
  SLACK_SIGNING_SECRET: ${slack-signing-secret}
