apiVersion: v1
kind: Service
metadata:
  name: {{ include ".helm.fullname" . }}
  {{- if eq .Values.service.type "LoadBalancer" }}
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.environment.fqdn }}
  {{- end }}
  labels:
    app.kubernetes.io/name: {{ include ".helm.name" . }}
    helm.sh/chart: {{ include ".helm.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include ".helm.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
