# Default values for .helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
apiVersion: apps/v1

image:
  repository: ''
  tag: ''
  pullPolicy: IfNotPresent

nameOverride: ''
fullnameOverride: ''

environment:
  name: ''
  ilEnvironmentName: ''

service:
  type: ClusterIP
  port: 80

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

probes:
  initialDelaySeconds: 10
  periodSeconds: 10
  path: /__/health

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 60

virtualService:
  clusterSubdomain: 'platform.infinicloud.net'
  externalHostname: 'slack-bot.infinicloud.app'
