name: Build and push Docker image

on:
  workflow_call:
    inputs:
      docker-registry:
        description: 'Docker registry'
        type: string
        required: true
      image-name:
        description: 'Image name'
        type: string
        required: true
      image-tag:
        description: 'Image tag'
        type: string
        required: true

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .npmrc
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{secrets.IL_NPM_INFINITASLEARNING_GITHUB_READONLY_TOKEN}}" >> .npmrc

      - name: 'Build Docker Image'
        run: >-
          docker build 
          -t ${{ inputs.docker-registry }}/${{ inputs.image-name }}:${{ inputs.image-tag }} 
          -t ${{ inputs.docker-registry }}/${{ inputs.image-name }}:latest
          .

      - name: Push docker image to ACR
        run: |
          az acr login -u ${{ secrets.ACR_ILWEBSHOPS_USERNAME }} -p ${{ secrets.ACR_ILWEBSHOPS_PASSWORD }} -n ${{ inputs.docker-registry }}
          docker push ${{ inputs.docker-registry }}/${{ inputs.image-name }} --all-tags
