name: Main deployment

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-push:
    uses: ./.github/workflows/build-push.yml
    with:
      docker-registry: ilwebshops.azurecr.io
      image-name: ${{ github.repository }}
      image-tag: ${{ github.sha }}
    secrets: inherit
  deploy-production:
    needs: [build-push]
    name: Deploy to production
    uses: ./.github/workflows/k8s-deploy.yml
    with:
      il-env: production
      short-env: prd
      cluster-name: il-k8s-platform
    secrets: inherit
